from datetime import datetime
from typing import Any

import pandas as pd

class BinanceDataCollector:
    def __init__(self) -> None: ...
    def get_available_symbols(self) -> list[str]: ...
    def fetch_ohlcv(self, symbol: str, timeframe: str = "1h", since: datetime | None = None, limit: int | None = None) -> pd.DataFrame: ...
    def fetch_historical_data(self, symbol: str, timeframe: str = "1h", days_back: int = 30) -> pd.DataFrame: ...
    def save_to_database(self, symbol: str, df: pd.DataFrame, timeframe: str = "1h") -> None: ...
    def collect_and_save(self, symbols: list[str], timeframe: str = "1h", days_back: int = 30) -> None: ...
    def get_latest_prices(self, symbols: list[str]) -> dict[str, float | None]: ...
    def get_market_info(self, symbol: str) -> dict[str, Any]: ...

def main() -> None: ...
